title: Zhengyu Zhao<br><font style="font-family:隶书" size="5">(赵正宇)</font>
position: Postdoc
affiliation: CISPA Helmholtz Center for Information Security
affiliation_link: https://cispa.de/en
email: zhengyu.zhao (at) cispa.de
keywords: zhengyu zhao, zhao zhengyu, zhengyuzhao, zhaozhengyu
google_scholar: https://scholar.google.com/citations?user=pC8KpPMAAAAJ&hl=en
# cv_link: https://files.yliu.de/Yaoyao_Liu_Resume.pdf
github_link: https://github.com/ZhengyuZhao
linkedin: https://www.linkedin.com/in/zhengyu-zhao-61361a8a/
twitter: https://twitter.com/JeremyZhaozy
avatar: ./assets/img/IMG_self_2.jpg
google_analytics: UA-111540567-4
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png
description: Zhengyu Zhao is a Postdoctoral researcher at CISPA Helmholtz Center for Information Security. His research lies in AI Security and Privacy, Adversarial Machine Learning, Adversarial Examples, and Computer Vision.
# canonical: ZhengyuZhao.github.io
# imprint: https://imprint.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu
# data_protection: https://data-protection.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu?lang=en

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
