title: Jie Lou
position: PhD researcher
affiliation: IDS, RWTH Aachen University
affiliation_link: https://www.ids.rwth-aachen.de/en/
email: lou@ids.rwth-aachen.de
keywords: jie lou, lou jie, loujie, jielou, Jie Lou, Lou Jie, LouJie, JieLou

google_scholar: https://scholar.google.com/citations?user=hc48V2MAAAAJ&hl=en
# github_link: https://github.com/ZhengyuZhao
linkedin: https://www.linkedin.com/in/jie-lou-a17bbb160/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/lou.jpg
google_analytics: UA-111540567-4
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
